{
 "title": "Stafi Dashboard",
 "description": "kusama",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "kusama" },
   {
    "name": "nodeport",
    "label": "Node:port",
    "query": "label_values(polkadot_block_height{job=~\"$job\"},instance)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "block Sync rate [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_block_height[5m])",
     "legendFormat": "{{status}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Number of network sync peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_peers_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "polkadot_block_height{instance=~\"$nodeport\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "polkadot_network_per_sec_bytes{instance=~\"$nodeport\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "polkadot_memory_usage_bytes{instance=~\"$nodeport\"}",
     "legendFormat": "Node memory usage"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "polkadot_cpu_usage_percentage{instance=~\"$nodeport\"}",
     "legendFormat": "Node CPU usage"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "polkadot_load_avg{instance=~\"$nodeport\"}",
     "legendFormat": "{{over}}"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_netstat_tcp{instance=~\"$nodeport\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of network sync peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_peers_count{instance=~\"$nodeport\"}",
     "legendFormat": "Peers count"
    },
    {
     "expr": "polkadot_sub_libp2p_peerset_num_discovered{instance=~\"$nodeport\"}",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "polkadot_sub_libp2p_peerset_num_requested{instance=~\"$nodeport\"}",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_finality_grandpa_communication_gossip_validator_messages{instance=~\"$nodeport\"}[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_tasks_polling_started_total{instance=~\"$nodeport\"} - polkadot_tasks_polling_duration_count{instance=~\"$nodeport\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sync_queued_blocks{instance=~\"$nodeport\"}",
     "legendFormat": "Queued Blocks (sync)"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "polkadot_ready_transactions_number{instance=~\"$nodeport\"}",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  }
 ]
}