{
 "title": "XX Network - Alerts",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block Sync Rate 10m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_block_height{job=~\".*xxnetwork.*\",status=\"finalized\"}[10m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Block height target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{job=~\".*xxnetwork.*\",status=\"sync_target\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sync_peers{job=~\".*xxnetwork.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Port is UP",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"xxnetwork\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Linux Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (host) (irate(node_cpu_seconds_total{mode=\"idle\", job=~\".*xxnetwork.*\"}[5m])) * 100)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_free_bytes{job=~\".*xxnetwork.*\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{job=~\".*xxnetwork.*\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{job=~\".*xxnetwork.*\"} - node_memory_MemFree_bytes{job=~\".*xxnetwork.*\"} - node_memory_Buffers_bytes{job=~\".*xxnetwork.*\"} - node_memory_Cached_bytes{job=~\".*xxnetwork.*\"}) / node_memory_MemTotal_bytes{job=~\".*xxnetwork.*\"} ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Predicted Available Gb in 7 days",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_avail_bytes{job=~\".*xxnetwork.*\",fstype=~\"ext4|xfs\"}[24h],7*24*3600)/1024/1024/1024",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}